cmd_scripts/perl/Perf-Trace-Util/Context.o := gcc -Wp,-MD,scripts/perl/Perf-Trace-Util/.Context.o.d,-MT,scripts/perl/Perf-Trace-Util/Context.o  -Wbad-function-cast -Wdeclaration-after-statement -Wformat-security -Wformat-y2k -Winit-self -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-system-headers -Wold-style-definition -Wpacked -Wredundant-decls -Wshadow -Wstrict-aliasing=3 -Wstrict-prototypes -Wswitch-default -Wswitch-enum -Wundef -Wwrite-strings -Wformat -DHAVE_ARCH_X86_64_SUPPORT -DHAVE_SYSCALL_TABLE -Iarch/x86/include/generated -DHAVE_PERF_REGS_SUPPORT -DHAVE_ARCH_REGS_QUERY_REGISTER_OFFSET -Werror -fno-omit-frame-pointer -ggdb3 -funwind-tables -Wall -Wextra -std=gnu99 -fstack-protector-all -I/home/taeung/git/taeung/linux-perf/tools/perf/util/include -I/home/taeung/git/taeung/linux-perf/tools/perf/arch/x86/include -I/home/taeung/git/taeung/linux-perf/tools/include/uapi -I/home/taeung/git/taeung/linux-perf/tools/include/ -I/home/taeung/git/taeung/linux-perf/tools/arch/x86/include/uapi -I/home/taeung/git/taeung/linux-perf/tools/arch/x86/include/ -I/home/taeung/git/taeung/linux-perf/tools/arch/x86/ -I/home/taeung/git/taeung/linux-perf/tools/perf/util -I/home/taeung/git/taeung/linux-perf/tools/perf -I/home/taeung/git/taeung/linux-perf/tools/lib/ -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -DHAVE_SYNC_COMPARE_AND_SWAP_SUPPORT -DHAVE_PTHREAD_ATTR_SETAFFINITY_NP -DHAVE_DWARF_GETLOCATIONS -DHAVE_LIBELF_SUPPORT -DHAVE_LIBELF_MMAP_SUPPORT -DHAVE_ELF_GETPHDRNUM_SUPPORT -DHAVE_GELF_GETNOTE_SUPPORT -DHAVE_ELF_GETSHDRSTRNDX_SUPPORT -DHAVE_DWARF_SUPPORT  -DHAVE_LIBBPF_SUPPORT -DHAVE_BPF_PROLOGUE -DHAVE_SDT_EVENT -DHAVE_JITDUMP -DHAVE_DWARF_UNWIND_SUPPORT -DNO_LIBUNWIND_DEBUG_FRAME -DHAVE_LIBUNWIND_SUPPORT  -DHAVE_LIBAUDIT_SUPPORT -DHAVE_LIBCRYPTO_SUPPORT -I/usr/include/slang -DHAVE_SLANG_SUPPORT -DHAVE_GTK2_SUPPORT -DHAVE_TIMERFD_SUPPORT -DHAVE_LIBBFD_SUPPORT -DHAVE_ZLIB_SUPPORT -DHAVE_LZMA_SUPPORT -DHAVE_BACKTRACE_SUPPORT -DHAVE_LIBNUMA_SUPPORT -DHAVE_KVM_STAT_SUPPORT -DHAVE_AUXTRACE_SUPPORT -D"BUILD_STR(s)=\#s" -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -I/usr/lib/x86_64-linux-gnu/perl/5.22/CORE  -Wno-redundant-decls -Wno-strict-prototypes -Wno-unused-parameter -Wno-nested-externs -Wno-undef -Wno-switch-default -Wno-shadow  -c -o scripts/perl/Perf-Trace-Util/Context.o scripts/perl/Perf-Trace-Util/Context.c

source_scripts/perl/Perf-Trace-Util/Context.o := scripts/perl/Perf-Trace-Util/Context.c

deps_scripts/perl/Perf-Trace-Util/Context.o := \
  /usr/include/stdc-predef.h \
  /usr/lib/gcc/x86_64-linux-gnu/5/include/stdbool.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/EXTERN.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/perl.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/config.h \
  /usr/include/x86_64-linux-gnu/sys/types.h \
  /usr/include/features.h \
  /usr/include/x86_64-linux-gnu/sys/cdefs.h \
  /usr/include/x86_64-linux-gnu/bits/wordsize.h \
  /usr/include/x86_64-linux-gnu/gnu/stubs.h \
  /usr/include/x86_64-linux-gnu/gnu/stubs-64.h \
  /usr/include/x86_64-linux-gnu/bits/types.h \
  /usr/include/x86_64-linux-gnu/bits/typesizes.h \
  /usr/include/time.h \
  /usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h \
  /usr/include/endian.h \
  /usr/include/x86_64-linux-gnu/bits/endian.h \
  /usr/include/x86_64-linux-gnu/bits/byteswap.h \
  /usr/include/x86_64-linux-gnu/bits/byteswap-16.h \
  /usr/include/x86_64-linux-gnu/sys/select.h \
  /usr/include/x86_64-linux-gnu/bits/select.h \
  /usr/include/x86_64-linux-gnu/bits/sigset.h \
  /usr/include/x86_64-linux-gnu/bits/time.h \
  /usr/include/x86_64-linux-gnu/sys/sysmacros.h \
  /usr/include/x86_64-linux-gnu/bits/pthreadtypes.h \
  /usr/lib/gcc/x86_64-linux-gnu/5/include/stdarg.h \
  /usr/lib/gcc/x86_64-linux-gnu/5/include/stdint.h \
  /usr/include/stdint.h \
  /usr/include/x86_64-linux-gnu/bits/wchar.h \
  /usr/include/ctype.h \
  /usr/include/xlocale.h \
  /usr/include/locale.h \
  /usr/include/x86_64-linux-gnu/bits/locale.h \
  /usr/include/setjmp.h \
  /usr/include/x86_64-linux-gnu/bits/setjmp.h \
  /usr/include/x86_64-linux-gnu/sys/param.h \
  /usr/lib/gcc/x86_64-linux-gnu/5/include-fixed/limits.h \
  /usr/lib/gcc/x86_64-linux-gnu/5/include-fixed/syslimits.h \
  /usr/include/limits.h \
  /usr/include/x86_64-linux-gnu/bits/posix1_lim.h \
  /usr/include/x86_64-linux-gnu/bits/local_lim.h \
  /usr/include/linux/limits.h \
  /usr/include/x86_64-linux-gnu/bits/posix2_lim.h \
  /usr/include/x86_64-linux-gnu/bits/xopen_lim.h \
  /usr/include/x86_64-linux-gnu/bits/stdio_lim.h \
  /usr/include/signal.h \
  /usr/include/x86_64-linux-gnu/bits/signum.h \
  /usr/include/x86_64-linux-gnu/bits/siginfo.h \
  /usr/include/x86_64-linux-gnu/bits/sigaction.h \
  /usr/include/x86_64-linux-gnu/bits/sigcontext.h \
  /usr/include/x86_64-linux-gnu/bits/sigstack.h \
  /usr/include/x86_64-linux-gnu/sys/ucontext.h \
  /usr/include/x86_64-linux-gnu/bits/sigthread.h \
  /usr/include/x86_64-linux-gnu/bits/param.h \
  /usr/include/linux/param.h \
  /usr/include/x86_64-linux-gnu/asm/param.h \
  /usr/include/asm-generic/param.h \
  /usr/include/stdlib.h \
  /usr/include/x86_64-linux-gnu/bits/waitflags.h \
  /usr/include/x86_64-linux-gnu/bits/waitstatus.h \
  /usr/include/alloca.h \
  /usr/include/x86_64-linux-gnu/bits/stdlib-float.h \
  /usr/include/unistd.h \
  /usr/include/x86_64-linux-gnu/bits/posix_opt.h \
  /usr/include/x86_64-linux-gnu/bits/environments.h \
  /usr/include/x86_64-linux-gnu/bits/confname.h \
  /usr/include/getopt.h \
  /usr/include/x86_64-linux-gnu/sys/wait.h \
  /usr/include/string.h \
  /usr/include/netinet/in.h \
  /usr/include/x86_64-linux-gnu/sys/socket.h \
  /usr/include/x86_64-linux-gnu/sys/uio.h \
  /usr/include/x86_64-linux-gnu/bits/uio.h \
  /usr/include/x86_64-linux-gnu/bits/socket.h \
  /usr/include/x86_64-linux-gnu/bits/socket_type.h \
  /usr/include/x86_64-linux-gnu/bits/sockaddr.h \
  /usr/include/x86_64-linux-gnu/asm/socket.h \
  /usr/include/asm-generic/socket.h \
  /usr/include/x86_64-linux-gnu/asm/sockios.h \
  /usr/include/asm-generic/sockios.h \
  /usr/include/x86_64-linux-gnu/bits/in.h \
  /usr/include/arpa/inet.h \
  /usr/include/x86_64-linux-gnu/sys/stat.h \
  /usr/include/x86_64-linux-gnu/bits/stat.h \
  /usr/include/x86_64-linux-gnu/bits/timex.h \
  /usr/include/x86_64-linux-gnu/sys/time.h \
  /usr/include/x86_64-linux-gnu/sys/times.h \
  /usr/include/errno.h \
  /usr/include/x86_64-linux-gnu/bits/errno.h \
  /usr/include/linux/errno.h \
  /usr/include/x86_64-linux-gnu/asm/errno.h \
  /usr/include/asm-generic/errno.h \
  /usr/include/asm-generic/errno-base.h \
  /usr/include/netdb.h \
  /usr/include/rpc/netdb.h \
  /usr/include/x86_64-linux-gnu/bits/netdb.h \
  /usr/include/x86_64-linux-gnu/sys/ioctl.h \
  /usr/include/x86_64-linux-gnu/bits/ioctls.h \
  /usr/include/x86_64-linux-gnu/asm/ioctls.h \
  /usr/include/asm-generic/ioctls.h \
  /usr/include/linux/ioctl.h \
  /usr/include/x86_64-linux-gnu/asm/ioctl.h \
  /usr/include/asm-generic/ioctl.h \
  /usr/include/x86_64-linux-gnu/bits/ioctl-types.h \
  /usr/include/x86_64-linux-gnu/sys/ttydefaults.h \
  /usr/include/dirent.h \
  /usr/include/x86_64-linux-gnu/bits/dirent.h \
  /usr/lib/gcc/x86_64-linux-gnu/5/include/float.h \
  /usr/include/math.h \
  /usr/include/x86_64-linux-gnu/bits/math-vector.h \
  /usr/include/x86_64-linux-gnu/bits/libm-simd-decl-stubs.h \
  /usr/include/x86_64-linux-gnu/bits/huge_val.h \
  /usr/include/x86_64-linux-gnu/bits/huge_valf.h \
  /usr/include/x86_64-linux-gnu/bits/huge_vall.h \
  /usr/include/x86_64-linux-gnu/bits/inf.h \
  /usr/include/x86_64-linux-gnu/bits/nan.h \
  /usr/include/x86_64-linux-gnu/bits/mathdef.h \
  /usr/include/x86_64-linux-gnu/bits/mathcalls.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/handy.h \
  /usr/include/inttypes.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/charclass_invlists.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/unixish.h \
  /usr/include/pthread.h \
  /usr/include/sched.h \
  /usr/include/x86_64-linux-gnu/bits/sched.h \
  /usr/include/assert.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/iperlsys.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/perlio.h \
  /usr/include/stdio.h \
  /usr/include/libio.h \
  /usr/include/_G_config.h \
  /usr/include/wchar.h \
  /usr/include/x86_64-linux-gnu/bits/sys_errlist.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/perly.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/sv.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/regexp.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/utf8.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/regcharclass.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/unicode_constants.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/op_reg_common.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/util.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/form.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/gv.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/pad.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/cv.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/opnames.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/op.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/reentr.h \
  /usr/include/pwd.h \
  /usr/include/grp.h \
  /usr/include/crypt.h \
  /usr/include/shadow.h \
  /usr/include/paths.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/hv.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/hv_func.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/cop.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/mydtrace.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/av.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/mg.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/scope.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/warnings.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/parser.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/patchlevel.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/intrpvar.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/thread.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/pp.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/proto.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/opcode.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/embedvar.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/embed.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/perlvars.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/mg_vtable.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/inline.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/overload.h \
  /usr/include/x86_64-linux-gnu/sys/ipc.h \
  /usr/include/x86_64-linux-gnu/bits/ipctypes.h \
  /usr/include/x86_64-linux-gnu/bits/ipc.h \
  /usr/include/x86_64-linux-gnu/sys/sem.h \
  /usr/include/x86_64-linux-gnu/bits/sem.h \
  /usr/include/x86_64-linux-gnu/sys/file.h \
  /usr/include/fcntl.h \
  /usr/include/x86_64-linux-gnu/bits/fcntl.h \
  /usr/include/x86_64-linux-gnu/bits/fcntl-linux.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/XSUB.h \
  /usr/lib/x86_64-linux-gnu/perl/5.22/CORE/perlapi.h \
  scripts/perl/Perf-Trace-Util/../../../perf.h \
  /home/taeung/git/taeung/linux-perf/tools/include/linux/types.h \
  /usr/include/x86_64-linux-gnu/asm/types.h \
  /usr/include/asm-generic/types.h \
  /usr/include/asm-generic/int-ll64.h \
  /home/taeung/git/taeung/linux-perf/tools/arch/x86/include/uapi/asm/bitsperlong.h \
  /home/taeung/git/taeung/linux-perf/tools/include/uapi/asm-generic/bitsperlong.h \
  /home/taeung/git/taeung/linux-perf/tools/include/uapi/linux/perf_event.h \
  /usr/include/x86_64-linux-gnu/asm/byteorder.h \
  /usr/include/linux/byteorder/little_endian.h \
  /usr/include/linux/swab.h \
  /home/taeung/git/taeung/linux-perf/tools/perf/util/include/asm/swab.h \
  scripts/perl/Perf-Trace-Util/../../../perf-sys.h \
  /usr/include/x86_64-linux-gnu/sys/syscall.h \
  /usr/include/x86_64-linux-gnu/asm/unistd.h \
  /home/taeung/git/taeung/linux-perf/tools/arch/x86/include/asm/unistd_64.h \
  /usr/include/x86_64-linux-gnu/bits/syscall.h \
  /home/taeung/git/taeung/linux-perf/tools/include/linux/compiler.h \
  /home/taeung/git/taeung/linux-perf/tools/include/asm/barrier.h \
  /home/taeung/git/taeung/linux-perf/tools/include/asm/../../arch/x86/include/asm/barrier.h \
  scripts/perl/Perf-Trace-Util/../../../util/target.h \
  scripts/perl/Perf-Trace-Util/../../../util/trace-event.h \
  /home/taeung/git/taeung/linux-perf/tools/lib/traceevent/event-parse.h \
  /usr/include/regex.h \
  scripts/perl/Perf-Trace-Util/../../../util/parse-events.h \
  /home/taeung/git/taeung/linux-perf/tools/include/linux/list.h \
  /home/taeung/git/taeung/linux-perf/tools/include/linux/poison.h \
  /home/taeung/git/taeung/linux-perf/tools/include/linux/kernel.h \

scripts/perl/Perf-Trace-Util/Context.o: $(deps_scripts/perl/Perf-Trace-Util/Context.o)

$(deps_scripts/perl/Perf-Trace-Util/Context.o):
